import { Injectable, NotFoundException, OnModuleInit } from '@nestjs/common';
import {
  ClarificationKind,
  ConfidenceLevel,
  PipelineStep,
  ServiceId,
  SourceRef,
  structuralElementExtractionSchema,
  type StructuralElementExtraction,
} from '@batione/shared';
import { PrismaService } from '../../common/prisma.service';
import { AuditService } from '../../common/audit.service';
import { TraceabilityService } from '../../common/traceability.service';
import { AiGatewayService } from '../../ai/ai-gateway.service';
import { ClarificationService } from '../../ai/clarification.service';
import { RulesService } from '../../rules/rules.service';
import { RebarCalculator, type RebarCalcInput } from '../../rules/rebar-calculator';
import { JobsService, type JobContext, type ServiceEngine } from '../../jobs/jobs.service';
import { ProjectsService } from '../../projects/projects.service';
import { AuthUser } from '../../auth/auth.decorators';

/**
 * Service 3 — Métré ferraillage.
 *
 * Division of labour is strict: the AI Gateway *reads* sections (dimensions and
 * rebar callouts) and the deterministic RebarCalculator *computes* lengths and
 * weights from BatiOne's versioned rules. No steel quantity is ever generated by
 * a language model.
 */
@Injectable()
export class RebarService implements ServiceEngine, OnModuleInit {
  readonly service = ServiceId.REBAR;

  constructor(
    private readonly prisma: PrismaService,
    private readonly gateway: AiGatewayService,
    private readonly clarifications: ClarificationService,
    private readonly rules: RulesService,
    private readonly calculator: RebarCalculator,
    private readonly jobs: JobsService,
    private readonly projects: ProjectsService,
    private readonly trace: TraceabilityService,
    private readonly audit: AuditService,
  ) {}

  onModuleInit(): void {
    this.jobs.registerEngine(this);
  }

  async run(ctx: JobContext): Promise<unknown> {
    await ctx.report(PipelineStep.IMPORT, 5, 'Lecture des plans de structure et des coupes…');

    await ctx.report(PipelineStep.ANALYSIS_2D, 22, 'Analyse des coupes…');

    const extraction = await this.gateway.extract<StructuralElementExtraction>({
      projectId: ctx.projectId,
      organizationId: ctx.organizationId,
      service: this.service,
      task: 'rebar.elements',
      schema: structuralElementExtractionSchema,
      schemaName: 'StructuralElement',
      instruction:
        "Relève les éléments structurels et leurs cartouches d'armatures sur les coupes. Restitue les dimensions lues et les cartouches tels qu'écrits (ex. « 4HA12 », « cadres HA8 e=20 »). Ne calcule NI longueur NI poids : le moteur de règles BatiOne s'en charge.",
      documentKinds: ['coupe', 'plan'],
    });

    await ctx.report(PipelineStep.SPECIFICATIONS, 40, 'Chargement des règles de calcul BatiOne…');
    const ruleSet = await this.rules.rebarRules(ctx.organizationId);

    await ctx.report(PipelineStep.DETECTION, 58, 'Identification des armatures…');

    await this.prisma.structuralElement.deleteMany({ where: { projectId: ctx.projectId } });

    const answers = await this.clarifications.resolvedValues(ctx.projectId, this.service);
    const stored: string[] = [];

    for (const element of extraction.items) {
      const dimensions = this.applyAnswers(element, answers);
      const sources = this.trace.normalizeSourceRefs(
        `rebar.${element.reference}`,
        element.sources,
      );
      // The same element often appears on several documents (a section and the
      // structural plan). That is corroboration, not a duplicate: merge the
      // source refs onto one element rather than creating two.
      const existing = await this.prisma.structuralElement.findUnique({
        where: {
          projectId_reference: {
            projectId: ctx.projectId,
            reference: element.reference,
          },
        },
      });

      const mergedSources = existing
        ? this.trace.mergeSources(this.trace.readSourceRefs(existing.sourceRefs), sources)
        : sources;

      const created = await this.prisma.structuralElement.upsert({
        where: {
          projectId_reference: {
            projectId: ctx.projectId,
            reference: element.reference,
          },
        },
        create: {
          projectId: ctx.projectId,
          reference: element.reference,
          type: element.type,
          floor: element.floor,
          count: element.count,
          dimensions: dimensions as never,
          callouts: element.callouts as never,
          confidence: this.trace.coerceConfidence(element.confidence, sources),
          sourceRefs: sources as never,
        },
        update: {
          count: Math.max(existing?.count ?? 0, element.count),
          dimensions: {
            ...((existing?.dimensions as Record<string, unknown>) ?? {}),
            ...dimensions,
          } as never,
          callouts: element.callouts as never,
          confidence: this.trace.coerceConfidence(element.confidence, mergedSources),
          sourceRefs: mergedSources as never,
        },
      });
      if (!stored.includes(created.id)) stored.push(created.id);
    }

    await ctx.report(PipelineStep.GENERATION, 78, 'Calcul déterministe du ferraillage…');
    const computed = await this.computeAll(ctx.projectId, ctx.organizationId);

    await ctx.report(PipelineStep.VERIFICATION, 93, 'Vérification et traçabilité…');

    return {
      elements: stored.length,
      rebarLines: computed.lineCount,
      totalWeightKg: computed.totalWeightKg,
      ruleSet: `${ruleSet.key}@${ruleSet.version}`,
    };
  }

  /**
   * Runs the deterministic calculator over every stored element. Elements whose
   * inputs are incomplete produce clarification questions and stay `blocked`
   * rather than yielding a partial weight that could be mistaken for a total.
   */
  async computeAll(projectId: string, organizationId: string) {
    const ruleSet = await this.rules.rebarRules(organizationId);
    const elements = await this.prisma.structuralElement.findMany({
      where: { projectId },
    });

    let lineCount = 0;
    let totalWeightKg = 0;
    const missingAll: { path: string; label: string }[] = [];

    // Answers given by the user are inputs like any other — with the strongest
    // confidence tier and their own traceable "source".
    const answers = await this.clarifications.resolvedValues(projectId, this.service);

    for (const element of elements) {
      await this.prisma.rebarLine.deleteMany({ where: { structuralElementId: element.id } });

      const input: RebarCalcInput = {
        reference: element.reference,
        type: element.type,
        count: element.count,
        dimensions: this.readDimensions(this.applyAnswers(
          {
            reference: element.reference,
            dimensions: (element.dimensions ?? {}) as Record<string, unknown>,
          } as never,
          answers,
        )),
        callouts: this.applyCalloutAnswers(
          element.reference,
          this.readCallouts(element.callouts),
          answers,
        ),
      };

      // A bar whose count or spacing came from an answered question must read
      // "confirmé par l'utilisateur", never "certain" — it was never on the plan.
      const confirmedBars = new Set(
        input.callouts
          .filter((c) => c.confidence === ConfidenceLevel.USER_CONFIRMED)
          .map((c) => `${c.role}:${c.diameterMm}`),
      );

      const { lines, missing } = this.calculator.compute(
        input,
        ruleSet.definition,
        ruleSet.id,
        ruleSet.version,
      );

      for (const line of lines) {
        await this.prisma.rebarLine.create({
          data: {
            structuralElementId: element.id,
            role: line.role,
            diameterMm: line.diameterMm,
            unitLengthM: line.unitLengthM,
            count: line.count,
            totalLengthM: line.totalLengthM,
            unitMassKgPerM: line.unitMassKgPerM,
            totalWeightKg: line.totalWeightKg,
            ruleId: line.ruleId,
            ruleVersion: line.ruleVersion,
            computation: line.computation,
            confidence: confirmedBars.has(`${line.role}:${line.diameterMm}`)
              ? ConfidenceLevel.USER_CONFIRMED
              : line.confidence,
            sourceRefs: this.trace.mergeSources(line.sources) as never,
          },
        });
        lineCount += 1;
        totalWeightKg += line.totalWeightKg;
      }

      await this.prisma.structuralElement.update({
        where: { id: element.id },
        data: { blocked: missing.length > 0 },
      });
      missingAll.push(...missing);
    }

    if (missingAll.length > 0) {
      await this.clarifications.persist(
        projectId,
        this.service,
        missingAll.map((entry) => ({
          kind: ClarificationKind.MISSING_DATA,
          targetPath: entry.path,
          question: `Le calcul de ferraillage nécessite ${entry.label}, qui n'a pas pu être relevé sur les documents. Quelle valeur retenir ?`,
          options: [],
          sources: [],
        })),
      );
    }

    return { lineCount, totalWeightKg: round3(totalWeightKg), missing: missingAll };
  }

  private applyAnswers(
    element: StructuralElementExtraction,
    answers: Map<string, { value: string; numeric: number | null }>,
  ): Record<string, unknown> {
    const dimensions: Record<string, unknown> = { ...element.dimensions };

    const lengthAnswer = answers.get(`rebar.${element.reference}.length`)?.numeric;
    if (lengthAnswer != null) {
      dimensions.length = {
        value: lengthAnswer,
        confidence: ConfidenceLevel.USER_CONFIRMED,
        sources: [
          {
            ruleId: 'user-clarification',
            ruleVersion: '1',
            note: `Longueur confirmée par l'utilisateur pour ${element.reference}`,
          } satisfies SourceRef,
        ],
      };
    }

    const sectionAnswer = answers.get(`rebar.${element.reference}.section`)?.value;
    if (typeof sectionAnswer === 'string') {
      const match = /(\d+(?:[.,]\d+)?)\s*[x×]\s*(\d+(?:[.,]\d+)?)/.exec(sectionAnswer);
      if (match) {
        let a = Number.parseFloat(match[1].replace(',', '.'));
        let b = Number.parseFloat(match[2].replace(',', '.'));
        if (a > 5 || b > 5) {
          a /= 100;
          b /= 100;
        }
        const source: SourceRef = {
          ruleId: 'user-clarification',
          ruleVersion: '1',
          note: `Section confirmée : ${sectionAnswer}`,
        };
        dimensions.width = {
          value: a,
          confidence: ConfidenceLevel.USER_CONFIRMED,
          sources: [source],
        };
        dimensions.height = {
          value: b,
          confidence: ConfidenceLevel.USER_CONFIRMED,
          sources: [source],
        };
      }
    }

    return dimensions;
  }

  /**
   * Fills call-out values the drawing did not state with the answers the user
   * gave to the clarification questions. The value is marked user_confirmed and
   * carries a source pointing at the answered question, so the number stays
   * auditable instead of appearing out of nowhere.
   */
  private applyCalloutAnswers(
    reference: string,
    callouts: RebarCalcInput['callouts'],
    answers: Map<string, { value: string; numeric: number | null }>,
  ): RebarCalcInput['callouts'] {
    return callouts.map((callout) => {
      const countAnswer = answers.get(`rebar.${reference}.count.${callout.raw}`)?.numeric;
      const spacingAnswer = answers.get(`rebar.${reference}.spacing.${callout.raw}`)?.numeric;
      if (countAnswer == null && spacingAnswer == null) return callout;

      const answerSource: SourceRef = {
        ruleId: 'user-clarification',
        ruleVersion: '1',
        note: `Valeur confirmée par l'utilisateur pour « ${callout.raw} » de ${reference}`,
      };

      return {
        ...callout,
        ...(countAnswer != null ? { count: countAnswer } : {}),
        // Spacings are answered in centimetres on site; anything above 1 is cm.
        ...(spacingAnswer != null
          ? { spacingM: spacingAnswer > 1 ? spacingAnswer / 100 : spacingAnswer }
          : {}),
        confidence: ConfidenceLevel.USER_CONFIRMED,
        sources: this.trace.mergeSources(callout.sources, [answerSource]),
      };
    });
  }

  private readDimensions(raw: unknown): RebarCalcInput['dimensions'] {
    const out: RebarCalcInput['dimensions'] = {};
    if (!raw || typeof raw !== 'object') return out;
    for (const [key, value] of Object.entries(raw as Record<string, unknown>)) {
      if (!value || typeof value !== 'object') continue;
      const traced = value as { value?: unknown; confidence?: string; sources?: unknown };
      if (typeof traced.value !== 'number') continue;
      out[key] = {
        value: traced.value,
        confidence: (traced.confidence as ConfidenceLevel) ?? ConfidenceLevel.DEDUCED,
        sources: Array.isArray(traced.sources) ? (traced.sources as SourceRef[]) : [],
      };
    }
    return out;
  }

  private readCallouts(raw: unknown): RebarCalcInput['callouts'] {
    if (!Array.isArray(raw)) return [];
    return raw
      .map((entry) => {
        const record = entry as Record<string, unknown>;
        const tracedNumber = (key: string): number | undefined => {
          const node = record[key] as { value?: unknown } | undefined;
          return typeof node?.value === 'number' ? node.value : undefined;
        };
        const rawNode = record.raw as { value?: unknown; sources?: unknown } | undefined;
        return {
          raw: typeof rawNode?.value === 'string' ? rawNode.value : '',
          role: (record.role as RebarCalcInput['callouts'][number]['role']) ?? 'longitudinal',
          diameterMm: tracedNumber('diameterMm'),
          count: tracedNumber('count'),
          spacingM: tracedNumber('spacingM'),
          confidence: ConfidenceLevel.CERTAIN,
          sources: Array.isArray(rawNode?.sources) ? (rawNode?.sources as SourceRef[]) : [],
        };
      })
      .filter((callout) => callout.raw.length > 0);
  }

  /* ---------------------------------------------------------------- */

  async read(projectId: string, organizationId: string) {
    await this.projects.assertOwned(projectId, organizationId);

    const elements = await this.prisma.structuralElement.findMany({
      where: { projectId },
      orderBy: [{ type: 'asc' }, { reference: 'asc' }],
      include: { rebarLines: { orderBy: { diameterMm: 'asc' } } },
    });

    const lines = elements.flatMap((element) =>
      element.rebarLines.map((line) => ({
        ...line,
        elementReference: element.reference,
        elementType: element.type,
        floor: element.floor,
      })),
    );

    const byDiameter = new Map<
      number,
      { totalLengthM: number; totalWeightKg: number; count: number }
    >();
    for (const line of lines) {
      const entry =
        byDiameter.get(line.diameterMm) ?? { totalLengthM: 0, totalWeightKg: 0, count: 0 };
      entry.totalLengthM = round3(entry.totalLengthM + line.totalLengthM);
      entry.totalWeightKg = round3(entry.totalWeightKg + line.totalWeightKg);
      entry.count += line.count;
      byDiameter.set(line.diameterMm, entry);
    }

    const ruleSet = await this.rules.rebarRules(organizationId);

    return {
      elements,
      lines,
      totals: {
        elementCount: elements.length,
        blockedCount: elements.filter((e) => e.blocked).length,
        lineCount: lines.length,
        totalWeightKg: round3(lines.reduce((acc, l) => acc + l.totalWeightKg, 0)),
        grandTotalWeightKg: round3(lines.reduce((acc, l) => acc + l.totalWeightKg, 0)),
        byDiameter: [...byDiameter.entries()]
          .map(([diameterMm, value]) => ({ diameterMm, ...value }))
          .sort((a, b) => a.diameterMm - b.diameterMm),
        ruleSet: { id: ruleSet.id, key: ruleSet.key, version: ruleSet.version, label: ruleSet.label },
      },
    };
  }

  /** Correction of a read dimension, followed by a full deterministic recompute. */
  async correctElement(
    elementId: string,
    user: AuthUser,
    dto: { field: string; value: unknown; reason?: string },
  ) {
    const element = await this.prisma.structuralElement.findFirst({
      where: { id: elementId, project: { organizationId: user.organizationId } },
    });
    if (!element) throw new NotFoundException('Élément structurel introuvable.');

    const dimensions = { ...(element.dimensions as Record<string, unknown>) };
    const data: Record<string, unknown> = {};
    let previousValue: unknown;

    if (['length', 'width', 'height', 'depth', 'thickness'].includes(dto.field)) {
      const value = Number(dto.value);
      if (!Number.isFinite(value) || value <= 0) {
        throw new NotFoundException('Dimension invalide.');
      }
      previousValue = (dimensions[dto.field] as { value?: unknown })?.value ?? null;
      dimensions[dto.field] = {
        value,
        confidence: ConfidenceLevel.USER_CONFIRMED,
        sources: [
          {
            ruleId: 'user-correction',
            ruleVersion: '1',
            note: dto.reason ?? `Corrigé par ${user.fullName}`,
          },
        ],
      };
      data.dimensions = dimensions;
    } else if (dto.field === 'count') {
      previousValue = element.count;
      data.count = Math.max(1, Math.round(Number(dto.value)));
    } else if (dto.field === 'type' || dto.field === 'floor' || dto.field === 'reference') {
      previousValue = (element as unknown as Record<string, unknown>)[dto.field];
      data[dto.field] = String(dto.value ?? '');
    } else {
      throw new NotFoundException(`Champ « ${dto.field} » non modifiable.`);
    }

    await this.prisma.structuralElement.update({
      where: { id: element.id },
      data: {
        ...data,
        confidence: ConfidenceLevel.USER_CONFIRMED,
        correctionHistory: this.trace.appendCorrection(element.correctionHistory, {
          field: dto.field,
          previousValue,
          newValue: dto.value,
          previousConfidence: element.confidence as ConfidenceLevel,
          actorId: user.id,
          reason: dto.reason,
        }) as never,
      } as never,
    });

    await this.audit.record({
      organizationId: user.organizationId,
      projectId: element.projectId,
      actorId: user.id,
      service: this.service,
      action: 'rebar.correct',
      entityType: 'StructuralElement',
      entityId: element.id,
      payload: { field: dto.field, previousValue, newValue: dto.value },
    });

    await this.computeAll(element.projectId, user.organizationId);
    return this.read(element.projectId, user.organizationId);
  }

  async recompute(projectId: string, user: AuthUser) {
    await this.projects.assertOwned(projectId, user.organizationId);
    await this.computeAll(projectId, user.organizationId);
    return this.read(projectId, user.organizationId);
  }
}

function round3(value: number): number {
  return Math.round(value * 1000) / 1000;
}
